### PR TITLE
Port to flint 2.7 API changes

### PR DESCRIPTION
**Pull request by antonio-rojas**
Make it build and pass tests after flint 2.7 API changes

Part of #154

Since ANTIC now supports FLINT 2.6 and FLINT 2.7, we'll also support FLINT 2.6 for the time being.

Needs:

* [x] https://github.com/conda-forge/antic-feedstock/pull/3 for the CI to pass
* [x] https://github.com/conda-forge/arb-feedstock/pull/23 for the CI to pass

### CODE REVIEW

**Comment by saraedum** [comment]
@antonio-rojas is this compatible with earlier versions of FLINT? Or do we need to add some ifdefs here to make this work for all versions?

**Comment by antonio-rojas** [comment]
> @antonio-rojas is this compatible with earlier versions of FLINT? Or do we need to add some ifdefs here to make this work for all versions?

I don't think it is. But note that the antic commit that ports to flint 2.7 https://github.com/wbhart/antic/commit/2d6a93c1b34d545abf98f1b2d6fe85ecf281b7a9 doesn't care about older flint, so you would also have to add some ifdef's to upstream antic if you want to support both versions.

**Comment by saraedum** [comment]
Thanks for the info. @videlec so should we require FLINT 2.7 and the latest ANTIC?

**Comment by thierry-FreeBSD** [comment]
This patch applied to 1.0.0-RC12 fixes the problem: https://github.com/flatsurf/e-antic/issues/154 can be closed.

**Pull request merged**
