### PR TITLE
Replace recommended conda setup for developers with pixi

### PR DESCRIPTION
**Pull request by saraedum**
Our conda/mamba setup has always been a bit flaky in the CI. When new packages get released in conda-forge, workflows can randomly start to fail. This could be fixed with a conda lock file but pixi wraps this feature and some others in an easier to use package.

This also provides developers with an opinionated setup that does not require developers to understand how to sync their local environments with the setup used in the CI.

For packagers this does not change anything. This is still an autoconfiscated package.

### CODE REVIEW

**Comment by saraedum** [comment]
@videlec this is not completely done yet, but you might want to have a look already at the README [here](https://github.com/saraedum/e-antic/tree/pixi) and see if that makes sense to you. (cc @slel if you're curious what's the next conda-thing…)

**Comment by saraedum** [comment]
@wlav is there a race condition in cppyy when multiple processes try to build the allDict?

```
  Traceback (most recent call last):
    File "/home/runner/work/e-antic/e-antic/.pixi/envs/pyeantic-sagemath-95/lib/python3.9/shutil.py", line 803, in move
      os.rename(src, real_dst)
  FileNotFoundError: [Errno 2] No such file or directory: '/tmp/allDict_rdict.pch' -> '/home/runner/work/e-antic/e-antic/.pixi/envs/pyeantic-sagemath-95/lib/python3.9/site-packages/cppyy_backend/etc/allDict.cxx.pch.6.30.0'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/home/runner/work/e-antic/e-antic/.pixi/envs/pyeantic-sagemath-95/lib/python3.9/site-packages/cppyy_backend/etc/dictpch/makepch.py", line 150, in <module>
      ret = makepch()
    File "/home/runner/work/e-antic/e-antic/.pixi/envs/pyeantic-sagemath-95/lib/python3.9/site-packages/cppyy_backend/etc/dictpch/makepch.py", line 144, in makepch
      shutil.move(os.path.join(tmpdir, "allDict_rdict.pch"), pchFileName)
    File "/home/runner/work/e-antic/e-antic/.pixi/envs/pyeantic-sagemath-95/lib/python3.9/shutil.py", line 817, in move
      copy_function(src, real_dst)
    File "/home/runner/work/e-antic/e-antic/.pixi/envs/pyeantic-sagemath-95/lib/python3.9/shutil.py", line 432, in copy2
      copyfile(src, dst, follow_symlinks=follow_symlinks)
    File "/home/runner/work/e-antic/e-antic/.pixi/envs/pyeantic-sagemath-95/lib/python3.9/shutil.py", line 261, in copyfile
      with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
  FileNotFoundError: [Errno 2] No such file or directory: '/tmp/allDict_rdict.pch'
  /home/runner/work/e-antic/e-antic/.pixi/envs/pyeantic-sagemath-95/lib/python3.9/site-packages/cppyy_backend/loader.py:141: UserWarning: Precompiled header may be out of date (failed to build).
    warnings.warn('Precompiled header may be out of date (%s).' % msg)
```

**Comment by wlav** [comment]
Yes, I would think so. The build process itself will use a unique temporary name, but the final name is just the one, so if two are building at the same time, then that would clash. That said, shouldn't pip use a temporary build directory? Meaning that although the final name is the same, so the copy would overwrite, the move shouldn't, as each would be from it's own build directory and not from `/tmp`?

**Comment by wlav** [comment]
Completely aside, while I have your attention, I'm very close to finishing up LLVM16. I'm traveling again for the rest of this week, but hope to find time next week. That should resolve the Mac problems (I'd hope).

**Comment by saraedum** [comment]
> Yes, I would think so. The build process itself will use a unique temporary name, but the final name is just the one, so if two are building at the same time, then that would clash.

Maybe we patched something bad into cppyy-backend at conda-forge, but that /tmp/ path does not look very unique to me.

> That said, shouldn't pip use a temporary build directory? Meaning that although the final name is the same, so the copy would overwrite, the move shouldn't, as each would be from it's own build directory and not from `/tmp`?

There's no pip involved here. This just happens the first time a `import cppyy` happens.

So, for some reason, conda-forge does not ship the allDict file but deletes it: https://github.com/conda-forge/cppyy-cling-feedstock/blob/main/recipe/build.sh#L103

Should that be changed?

**Comment by wlav** [comment]
Oh, found it (I think) ... `makepch.py` (which is called from both `import cppyy` as well as the build process) calls `tmpdir = tempfile.gettempdir()`, which on e.g. Mac returns an unique directory, but on Linux returns simply `/tmp`. This should probably be changed to use `mkdtemp()`.

Yes, it's not shipped. The original motivation was that it was simply too big (PyPI would not allow the wheel upload, as it was over their limit). Later, `-march=native` was added for Linux, which is non-portable, so after that, it shouldn't be shipped anymore.

**Comment by saraedum** [comment]
@wlav so, I guess there is some logic that tries to rebuild these files when compiler flags change?

I am running `import cppyy` explicitly which produces

```
(Re-)building pre-compiled headers (options: -O2 -march=native); this may take a minute ...
```

But then later I run a couple of tests in parallel that cause:

```
(Re-)building pre-compiled headers (options:-I/home/runner/work/e-antic/e-antic/pyeantic/test/../../libeantic -I/home/runner/work/e-antic/e-antic/pyeantic/test/../../libeantic/e-antic -Wno-macro-redefined ); this may take a minute ...
```

And then things crash. (Segfault on Linux, compile errors on macOS.)

**Comment by wlav** [comment]
It checks a limited subset of compiler flags, yes, but those only change if you set EXTRA_CLING_ARGS. Otherwise, it only checks the time stamp of the `include` directory in `cppyy_backend`. Basically, the "up to date" check is no more than this: `return os.stat(pchname).st_mtime >= os.stat(incpath).st_mtime`.

The compiler flags are checked b/c things like openmp, avx, and cuda get "baked in" since they define specific macros that bring in different runtime/instrinsics, so you can't simply switch them on/off while keeping the PCH the same.

**Comment by saraedum** [comment]
Ok. Thanks. I think I can work around the remaining issues myself now :)

**Comment by wlav** [comment]
LLVM16 works on Linux and Mac (all tests passing). MS is not providing any VM images currently (https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/), so can't test on that platfiorm. The CI builds show a weird failure in MSVC's own headers. So done with that platform. :/

Next week, I'm losing access to my Linux servers b/c of an electrical upgrade to the building. If afterwards MS still doesn't provide images, I'm going to create a release anyway w/o Windows support.

**Pull request merged**
