### PR TITLE
Add Continuous Integration with Sage

### PR DESCRIPTION
**Pull request by mkoeppe**
Preview: https://github.com/mkoeppe/e-antic/actions/runs/152354380

### CODE REVIEW

**Comment by videlec** [comment]
What is this supposed to achieve? Shouldn't integration within Sage be done in Sage?

**Comment by mkoeppe** [comment]
It adds portability testing.

**Comment by mkoeppe** [comment]
And it provides the "I" in "CI".

**Comment by saraedum** [comment]
I don't think this will work after #102. libflint from ubuntu is not sufficiently recent I am afraid. Also there's no antic.

**Comment by saraedum** [comment]
I don't fully understand what this is supposed to do actually. Does this test that e-antic can be installed within SageMath?

**Comment by mkoeppe** [comment]
> I don't think this will work after #102. libflint from ubuntu is not sufficiently recent I am afraid. Also there's no antic.

The pull request is for master0. I haven't followed whatever is happening on master. Is there any software using it?

**Comment by mkoeppe** [comment]
> I don't fully understand what this is supposed to do actually. Does this test that e-antic can be installed within SageMath?

See https://github.com/mkoeppe/e-antic/runs/821200908

It builds and tests e-antic on many platforms. 
For example, in the cygwin-standard test (https://github.com/mkoeppe/e-antic/runs/821200726), it reveals a build error.

It then proceeds to build and test Normaliz.

For all of this it uses the new Sage portability testing infrastructure. It runs e-antic's "make dist" and then replaces the e-antic package of Sage by the newly packaged one.

It does not build Sage itself.

**Comment by saraedum** [comment]
Thanks for the clarifications. That sounds like a very reasonable thing to do. I am not sure we want to invest much work in fixing build/distribution issues in `master0` but it would be very nice to have this kind of test for 1.0.0 eventually.

I don't really understand github actions but why is this big workflow file needed? Isn't the idea to just pull in snippets from published actions for this?

**Comment by mkoeppe** [comment]
> I am not sure we want to invest much work in fixing build/distribution issues in `master0` [...]

Well, master0 is what is the one currently used in Normaliz and thus in Sage. And it currently has portability issues (see https://trac.sagemath.org/ticket/27952). By adding the portability testing here, one can reduce the turnaround time for fixing such issues.

> I don't really understand github actions but why is this big workflow file needed? Isn't the idea to just pull in snippets from published actions for this?

Yes, that's right, that's the idea. The workflow is using some published actions such as actions/checkout@v2, actions/upload-artifact@v2 . It is possible that some refactoring can be done by publishing some sage-related actions. But this is only worth doing if enough projects accept the sage-based portability testing... (Also, there is a technical limitation there -- published actions either need to written in Javascript, or they will have to run in a Docker container.)

**Comment by mkoeppe** [comment]
I have added some documentation based on the explanations I gave above.

**Comment by mkoeppe** [comment]
This is a better version that I would think is suitable for inclusion. Results here: https://github.com/mkoeppe/e-antic/actions/runs/155744530

**Comment by saraedum** [comment]
I think it's fine to merge this into master0, however, we probably won't make too many changes there anymore.

For master itself, we need to bring antic (and the latest normaliz) to SageMath first. This will take quite some time I am afraid. Before we're done with that we can't run integration tests in a meaningful way I think.

**Pull request merged**
