### PR TITLE
Flint3

### LINKED ISSUE #263: flint 3 is out
flint3 was just released ant it is shipped with antic.

See https://github.com/sagemath/sage/pull/35848#issuecomment-1774031002

### PR DESCRIPTION
**Pull request by videlec**
Checklist
* [ ] Added an entry in `doc/news/`. 
* [ ] Added a test/benchmark for this change.

Update e-antic to work with the now released flint 3.0.0.

Fixes #263.

##### Dependencies

* [x] https://github.com/conda-forge/libflint-feedstock/pull/29

### CODE REVIEW

**Comment by videlec** [comment]
Of course, one would need flint 3.0.0 in conda.

**Comment by saraedum** [comment]
I think you need to adapt the tests so that it does not test with FLINT 2.6-2.9.

**Comment by videlec** [comment]
Hmm if we drop flint-2 we can not test with sage anymore (flint-3 is only available in sage 10.3.beta0).

**Comment by saraedum** [comment]
It won't be pretty but we can support FLINT 2 & 3 I guess?

**Comment by videlec** [comment]
Supporting flint 2 & 3 would indeed be nice.

**Comment by saraedum** [comment]
FLINT 2 & 3 is now in https://github.com/flatsurf/e-antic/pull/266. It works locally but something is not working out in the CI still.

**Pull request closed without merging**
